### ISSUE TITLE
Duplicated definitions in v8.7.2 cause error TS2349: This expression is not callable

### ISSUE THREAD

**Issue by caasi** [Popmotion/popmotion#878]
# Popmotion: duplicated definitions

## Describe the bug
After upgrade from v8.7.1 to v8.7.2 the following files in `node_modules/popmotion/` have duplicated definitions.

`lib/animations/tween.d.ts`:

```typescript
import { ForT } from '../types';
export interface TweenConfig {
    from?: number;
    to?: number;
    duration?: number;
    ease?: (t: number) => number;
}
export declare const tween: ({ from, to, duration, ease }?: TweenConfig) => ForT;
```

`lib/animations/tween/index.d.ts`:

```typescript
import { Action } from '../../action';
import { TweenInterface, TweenProps } from './types';
declare const tween: (props?: TweenProps) => Action<TweenInterface<number>>;
export default tween;
```

And it causes `error TS2349: This expression is not callable` in my project.

Remove `lib/animations/tween.d.ts` resolved this problem for me.

## How to reproduce
1. install popmotion v8.7.2
2. `import { tween } from 'popmotion';`

## Expected behaviour
`tsc` should not complain about error TS2349.

## Device information
In which environment are you reproducing the bug?
 - Device: MacBook Air
 - OS: macOS 10.15.4
 - TypeScript: 3.8.3

**Comment by InventingWithMonster** [comment]
Hmm that's weird, those definitions are from the Popmotion 9 beta, shouldn't even be in here 😅

Let me take a look now.

**Comment by InventingWithMonster** [comment]
Can you try `8.7.3` for me?

**Comment by caasi** [comment]
`8.7.3` works. Thank you!
